### ISSUE TITLE
Add level numbers to file names

### ISSUE THREAD

**Issue by pglutz** [ImperialCollegeLondon/complex-number-game#2]
I think it would be helpful to add numbers to the file names to indicate what level they are, much like in Patrick Massot's tutorial. E.g. 00-basic.lean, 01-I.lean, 02-conj.lean, etc.

**Comment by kbuzzard** [comment]
I can't import files whose names begin with numbers, or which have `-` signs in, so I've gone with `Level_03_conj.lean` etc
